leftnav:
- identifier: 165eea86-4929-5889-2f46-9ff9f2fbb0e3
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 52b17b1d-d7c3-db57-bc29-8992572134ee
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: f78b326a-d6e5-324e-dd13-34f4668286e9
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: a1ad4dd3-6d55-4a0d-de4e-652ee432038e
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 1b939335-29ca-86fe-6f77-0d4b8305733d
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
